EmployeeGateway/EmployeeGateway/urls.py
from django.conf.urls import url, include
from django.contrib import admin



from django.contrib.auth import views

urlpatterns = [
    url(r'', include("Gateway.urls", namespace="Gateway")),
    url(r'^admin/', admin.site.urls),
    
     url(r'^gateway/login/$', views.login, name='login'),
     url(r'^gateway/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),

]

EmployeeGateway/Gateway/urls.py
from django.conf.urls import url

from . import views
from django.views.generic import TemplateView
app_name='Gateway'

urlpatterns = [


url(r'^home/$', TemplateView.as_view(template_name="Employee/home.html"), name='homy'),

#this is for goverment portal for accesss of managers


url(r'^govt-signup/$', views.signup, name='signup'),




url(r'^govt-login/$', views.GovtLoginView.as_view(), name='govtlogin'),
url(r'^govt-home/$', views.GovtHome.as_view(), name='govthome'),

url(r'^govt-template/', views.UniversalIdentityNoCreateTemplate, name="govtcreatetemplate"),

url(r'^govt-create/', views.UniversalIdentityNoCreateView, name="govtcreated"),




# this is for managers

# url(r'^home/', views.Home.as_view(), name="home"),

url(r'^login/$', views.AdminLoginView.as_view(), name='login'),

url(r'^logouts/$', views.AdminLogoutView.as_view(), name='logout'),




url(r'^create/', views.EmployeeIdentificationNoCreateView.as_view(), name="create"),



url(r'^list/', views.EmployeeIdentificationNoListView.as_view(), name="employeelist"),

url(r'^home/details/(?P<pk>\d+)', views.EmployeeIdentificationNoDetailView.as_view(), name="detail"),





#payment gateway
url(r'^g$', TemplateView.as_view(template_name="Employee/PAYMENT.html"), name='g'),



# url(r'^add-money-to-wallet/', views.payment, name="add-money-to-wallet")


url(r'^transactionledger/(?P<pk>\d+)', views.Paymented.as_view(), name="transaction")







# url(r'^update/(?P<pk>\d+)', BusinessAdminUpdateView.as_view(), name="businessupdate"),
# url(r'^delete/(?P<pk>\d+)', BusinessAdminDeleteView.as_view(), name="businessdelete"),

    


]

EmployeeGateway/templates/base.html
<!DOCTYPE html>
<html>
  <head>

    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->

    <link type="text/css" href="{% static 'css/list.css' %}" rel="stylesheet" type="text/css" />


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>

{% if user.is_authenticated %}
    <a href="http://127.0.0.1:8000/gateway/login" > <h1>LOGOUT</h1> </a>
  {% else %}
  <a href="{% url 'Gateway:logout'  %}" > <h1>LOGIN</h1> </a>
{% endif %}

    <div class="container">
    {% block body_block %}
    {% endblock %}


    {% block content %}
    {% endblock %}
    </div>


    <script src="{% static 'js/list.js' %}" ></script>

  </body>
</html>