EmployeeGateway/EmployeeGateway/urls.py
from django.conf.urls import url, include
from django.contrib import admin



from django.contrib.auth import views

urlpatterns = [
    url(r'', include("Gateway.urls", namespace="Gateway")),
    url(r'^admin/', admin.site.urls),
    
     url(r'^gateway/login/$', views.login, name='login'),
     url(r'^gateway/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),

]

EmployeeGateway/Gateway/urls.py
from django.conf.urls import url

from . import views
from django.views.generic import TemplateView
app_name='Gateway'

urlpatterns = [


url(r'^home/$', TemplateView.as_view(template_name="Employee/home.html"), name='homy'),

#this is for goverment portal for accesss of managers


url(r'^govt-signup/$', views.signup, name='signup'),




url(r'^govt-login/$', views.GovtLoginView.as_view(), name='govtlogin'),
url(r'^govt-home/$', views.GovtHome.as_view(), name='govthome'),

url(r'^govt-template/', views.UniversalIdentityNoCreateTemplate, name="govtcreatetemplate"),

url(r'^govt-create/', views.UniversalIdentityNoCreateView, name="govtcreated"),




# this is for managers

# url(r'^home/', views.Home.as_view(), name="home"),

url(r'^login/$', views.AdminLoginView.as_view(), name='login'),

url(r'^logouts/$', views.AdminLogoutView.as_view(), name='logout'),




url(r'^create/', views.EmployeeIdentificationNoCreateView.as_view(), name="create"),



url(r'^list/', views.EmployeeIdentificationNoListView.as_view(), name="employeelist"),

url(r'^home/details/(?P<pk>\d+)', views.EmployeeIdentificationNoDetailView.as_view(), name="detail"),





#payment gateway
url(r'^g$', TemplateView.as_view(template_name="Employee/PAYMENT.html"), name='g'),



# url(r'^add-money-to-wallet/', views.payment, name="add-money-to-wallet")


url(r'^transactionledger/(?P<pk>\d+)', views.Paymented.as_view(), name="transaction")







# url(r'^update/(?P<pk>\d+)', BusinessAdminUpdateView.as_view(), name="businessupdate"),
# url(r'^delete/(?P<pk>\d+)', BusinessAdminDeleteView.as_view(), name="businessdelete"),

    


]

EmployeeGateway/templates/Employee/Employee-Login.html
{% extends 'base.html' %}
{% block body_block %}



<script type="text/javascript">
    
    console.log("reached");
</script>

    <form class="login-form" action="" method="post">
        
        {% csrf_token %}

        <input type="text" name="username">

        <input type="password" name="password">

        <input type="submit" class='btn btn-primary' value="Login" />


        
        
    </form>
   
{% endblock %}

EmployeeGateway/templates/Employee/EmployeeIdentification-detail.html
<!DOCTYPE html>
<html >
<head>
  {% load staticfiles %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/savings-122x122.png" type="image/x-icon">
  <meta name="description" content="Web Site Builder Description">
  <title>ADMIN HOME</title>

<link  href="{% static 'images/icons/savings.png' %}" rel="icon" type="image/png" />
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <link rel="stylesheet" href="{% static '/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'mobirise/css/mbr-additional.css' %}" type="text/css">


<style type="text/css">
  table{
    width:100%;
}
#example_filter{
    float:right;
}
#example_paginate{
    float:right;
}
label {
    display: inline-flex;
    margin-bottom: .5rem;
    margin-top: .5rem;
   
}

</style>

</head>
<body>
<section class="menu cid-rjijTCVSWR" once="menu" id="menu1-9">
    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                   <!--  <a href="adminHomeList.html">
                         <img src="assets/images/savings-122x122.png" alt="Mobirise" title="" style="height: 3.8rem;">
                    </a> -->
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="adminHomeList.html">EMPLOYEE GATEWAY</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item">
                    <a class="nav-link link text-white display-4" href="{% url 'Gateway:homy' %}">
                        <span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>HOME &nbsp; &nbsp;</a>
                </li><li class="nav-item">

                  <a class="nav-link link text-white display-4" href="{% url 'Gateway:transaction' pk=detail.pk %}"><span class="mbri-touch mbr-iconfont mbr-iconfont-btn"></span>Make a Payment to user</a>

                   <a class="nav-link link text-white display-4" href="http://127.0.0.1:8000/logouts"><span class="mbri-touch mbr-iconfont mbr-iconfont-btn"></span>\Logout</a>

                 <!--  <a class="nav-link link text-white display-4" href="adminPayment.html"><span class="mbri-touch mbr-iconfont mbr-iconfont-btn"></span>Create New User
                  </a> -->

                </li><!-- <li class="nav-item"><a class="nav-link link text-white display-4" href="userTransactionHistory.html"><span class="mbri-file mbr-iconfont mbr-iconfont-btn"></span>
                        TRANSACTION HISTORY&nbsp;</a></li> --></ul>
            
        </div>
    </nav>
</section>

<!------ Include the above in your HEAD tag ---------->

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>


<br><br><br><br><br><br>
<!-- <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names..">

    <a href="{% url 'Gateway:create' %}"><button>Create new user</button></a>

    <br>
    <br> -->

<div class="container">
  <div class="row">
  
        
<!-- 
  <table id="myTable" class="table table-striped table-bordered" style="width:100%">
  <tr class="header">
    <th style="width:60%;">Unique Identification key</th>
    <th style="width:40%;">Name</th>

  </tr>
       


  
  

  



  {% for attr in Attributes %}

            <tr class="header>
            <td>{{attr.pk}}</td>
                <td><a href="{% url 'Gateway:detail' pk=attr.pk  %} ">{{attr.employee_name}} </a></td>

           </tr>


  {% endfor %}  -->                      
            
      

    </table>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable(
        
         {     
      "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
        "iDisplayLength": 5
       } 
        );
} );


function checkAll(bx) {
  var cbs = document.getElementsByTagName('input');
  for(var i=0; i < cbs.length; i++) {
    if(cbs[i].type == 'checkbox') {
      cbs[i].checked = bx.checked;
    }
  }
}
</script>
  <script src="{% static '/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'popper/popper.min.js' %}"></script>
  <script src="{% static 'tether/tether.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'dropdown/js/script.min.js'%}"></script>
  <script src="{% static 'touchswipe/jquery.touch-swipe.min.js' %}"></script>
  <script src="{% static 'theme/js/script.js' %}"></script>
  
  
</body>
</html>









{% block body_block %}

<h1 style="text-align: center; color : red;">Details of Employee</h1>

<div class="yes">
	<hr>
<label> <h3 style="text-align: center">Name of employee</h3></label>
<br>

<h3 style="text-align: center"> {{ detail.employee_name}} </h3>

<hr>


<br>
<label> <h3 style="text-align: center">Contact no</h3></label>
<br>
<h3 style="text-align: center">{{ detail.contact_no}} </h3>

<hr>
<br>
<label> <h3 style="text-align: center">Bank account no</h3></label>
<br>
<h3 style="text-align: center">{{ detail.bank_accounts}}</h3>

<hr>



<br>
<label><h3 style="text-align: center">Bank IFSC code</h3></label>
	<br>
<h3 style="text-align: center">{{ detail.IFSC}}</h3>

<hr>

<br>
<label><h3 style="text-align: center">Bank name</h3></label>
<h3 style="text-align: center">{{ detail.bank}}</h3>

<hr>

<br>
<label><h3 style="text-align: center">Bank name</h3></label>
<h3 style="text-align: center">{{ detail.bank}}</h3>

<br>












</div>


<style type="text/css">
	.yes{

		position: absolute;
		top: 200px;
		left: 500px;
	}


</style>

{% endblock %}

EmployeeGateway/templates/Employee/EmployeeIdentification-list.html
<!DOCTYPE html>
<html >
<head>
  {% load staticfiles %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/savings-122x122.png" type="image/x-icon">
  <meta name="description" content="Web Site Builder Description">
  <title>ADMIN HOME</title>

<link  href="{% static 'images/icons/savings.png' %}" rel="icon" type="image/png" />
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <link rel="stylesheet" href="{% static '/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'mobirise/css/mbr-additional.css' %}" type="text/css">


<style type="text/css">
  table{
    width:100%;
}
#example_filter{
    float:right;
}
#example_paginate{
    float:right;
}
label {
    display: inline-flex;
    margin-bottom: .5rem;
    margin-top: .5rem;
   
}

</style>

</head>
<body>
<section class="menu cid-rjijTCVSWR" once="menu" id="menu1-9">
    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                   <!--  <a href="adminHomeList.html">
                         <img src="assets/images/savings-122x122.png" alt="Mobirise" title="" style="height: 3.8rem;">
                    </a> -->
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="adminHomeList.html">EMPLOYEE GATEWAY</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item">
                    <a class="nav-link link text-white display-4" href="{% url 'Gateway:homy' %}">
                        <span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>HOME &nbsp; &nbsp;</a>
                </li><li class="nav-item">

                  <a class="nav-link link text-white display-4" href="{% url 'Gateway:govtcreatetemplate' %}"><span class="mbri-touch mbr-iconfont mbr-iconfont-btn"></span>Create New User</a>

                  <a class="nav-link link text-white display-4" href="http://127.0.0.1:8000/logouts"><span class="mbri-touch mbr-iconfont mbr-iconfont-btn"></span>\Logout</a>

                 <!--  <a class="nav-link link text-white display-4" href="adminPayment.html"><span class="mbri-touch mbr-iconfont mbr-iconfont-btn"></span>Create New User
                  </a> -->

                </li><!-- <li class="nav-item"><a class="nav-link link text-white display-4" href="userTransactionHistory.html"><span class="mbri-file mbr-iconfont mbr-iconfont-btn"></span>
                        TRANSACTION HISTORY&nbsp;</a></li> --></ul>
            
        </div>
    </nav>
</section>

<!------ Include the above in your HEAD tag ---------->

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>


<br><br><br><br><br><br>
<!-- <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names..">

    <a href="{% url 'Gateway:create' %}"><button>Create new user</button></a>

    <br>
    <br> -->

<div class="container">
  <div class="row">
  
        
<!-- 
  <table id="myTable" class="table table-striped table-bordered" style="width:100%">
  <tr class="header">
    <th style="width:60%;">Unique Identification key</th>
    <th style="width:40%;">Name</th>

  </tr>
       


  
  

  



  {% for attr in Attributes %}

            <tr class="header>
            <td>{{attr.pk}}</td>
                <td><a href="{% url 'Gateway:detail' pk=attr.pk  %} ">{{attr.employee_name}} </a></td>

           </tr>


  {% endfor %}  -->                      
            
      

    </table>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable(
        
         {     
      "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
        "iDisplayLength": 5
       } 
        );
} );


function checkAll(bx) {
  var cbs = document.getElementsByTagName('input');
  for(var i=0; i < cbs.length; i++) {
    if(cbs[i].type == 'checkbox') {
      cbs[i].checked = bx.checked;
    }
  }
}
</script>
  <script src="{% static '/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'popper/popper.min.js' %}"></script>
  <script src="{% static 'tether/tether.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'dropdown/js/script.min.js'%}"></script>
  <script src="{% static 'touchswipe/jquery.touch-swipe.min.js' %}"></script>
  <script src="{% static 'theme/js/script.js' %}"></script>
  
  
</body>
</html>






{% block body_block %}





   
<script>
function myFunction() {
  // Declare variables
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>



<!-- search bar -->

    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names..">

    <!-- <a href="{% url 'Gateway:govthome' %}"><button>Create new user</button></a> -->

  </br>

</br>

<table id="myTable">
  <tr class="header">
    <th style="width:60%;">Unique Identification key</th>
    <th style="width:40%;">Name</th>

  </tr>


  {% for attr in Attributes %}

  
  <tr>
    <td>{{attr.unique_id}}</td>
    <td><a href="{% url 'Gateway:detail' pk=attr.pk  %} ">{{attr.name}} </a></td>
  </tr>

  

  {% endfor %}
  
</table> 


<style type="text/css">
  
  #myInput {
  background-image: url('/css/searchicon.png'); /* Add a search icon to input */
  background-position: 10px 12px; /* Position the search icon */
  background-repeat: no-repeat; /* Do not repeat the icon image */
  width: 100%; /* Full-width */
  font-size: 16px; /* Increase font-size */
  padding: 12px 20px 12px 40px; /* Add some padding */
  border: 1px solid #ddd; /* Add a grey border */
  margin-bottom: 12px; /* Add some space below the input */
}

#myTable {
  border-collapse: collapse; /* Collapse borders */
  width: 100%; /* Full-width */
  border: 1px solid #ddd; /* Add a grey border */
  font-size: 18px; /* Increase font-size */
}

#myTable th, #myTable td {
  text-align: left; /* Left-align text */
  padding: 12px; /* Add padding */
}

#myTable tr {
  /* Add a bottom border to all table rows */
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  /* Add a grey background color to the table header and on hover */
  background-color: #f1f1f1;
}
</style>




{% endblock %}



                                

EmployeeGateway/templates/Employee/PAYMENT.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<form  method="post" action="http://127.0.0.1:8000/add-money-to-wallet/" >

	<label>AMOUNT</label><input type="number" name="amount">
	<label>UNIQUE-ID</label><input type="number" id="unique_id" value={{iden}} name="unique_id">
	<label>TransactionTYpe</label><select name="transaction_type">
      
      <option value="ESI">ESI</option>
      <option value="PENSION">Pesnion</option>
      <option value="PF">PF</option>
  
    </select> 

    <button type="submit">Submit </button>

	

</form>


</body>
</html>

EmployeeGateway/templates/Employee/home.html
<!DOCTYPE html>
<html >
<head>

	{% load staticfiles %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.9.3, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static '/images/savings-122x122.png' %}" type="image/x-icon">
  <meta name="description" content="Site Generator Description">
  <title>Transaction History</title>
  <link rel="stylesheet" href="{% static '/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static '/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static '/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static '/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static '/theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static '/mobirise/css/mbr-additional.css' %}" type="text/css">
  
  
  
</head>
<body>
  <section class="menu cid-rjijTCVSWR" once="menu" id="menu1-5">

    

    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="#">
                         <imga src="{% static '/images/savings-122x122.png' %}" alt="Mobirise" title="" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="#">EMPLOYEE GATEWAY</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item">
                    <a class="nav-link link text-white display-4" href="{% url 'Gateway:homy' %}">
                        <span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>HOME &nbsp; &nbsp;</a>
 <a class="nav-link link text-white display-4" href="http://127.0.0.1:8000/logouts"><span class="mbri-touch mbr-iconfont mbr-iconfont-btn"></span>\Logout</a></li></ul>
            
        </div>
    </nav>
</section>

<section class="engine"><a href="https://mobirise.info/e">make a website</a></section><section class="header12 cid-rjDYfJFcqR mbr-fullscreen mbr-parallax-background" id="header12-f">

    

    <div class="mbr-overlay" style="opacity: 0.5; background-color: rgb(35, 35, 35);">
    </div>

    <div class="container  ">
            <div class="media-container">
                <div class="col-md-12 align-center">
                    <h1 class="mbr-section-title pb-3 mbr-white mbr-bold mbr-fonts-style display-1">
                        <br>EMPLOYEE GATEWAY</h1>
                    <p class="mbr-text pb-3 mbr-white mbr-fonts-style display-5">
                        A simplistic software platform which will help MSME sector to solve one of its major problem of having to maintain many records for a single employee's salary. Our model will enable employees to have single unique identification number and allow the caretakers to make ONE-CLICK payments of salary and maintain a ledger for individual payment accounts.</p>
                    

                    <div class="icons-media-container mbr-white">
                        <div class="card col-12 col-md-6 col-lg-4">
                            <div class="icon-block">
                            <a href="#">
                                <span class="mbr-iconfont mbri-map-pin"></span>
                            </a>
                            </div>
                            <h5 class="mbr-fonts-style display-5">One-Stop Solution</h5>
                        </div>

                        <div class="card col-12 col-md-6 col-lg-4">
                            <div class="icon-block">
                                <a href="#">
                                    <span class="mbr-iconfont mbri-touch"></span>
                                </a>
                            </div>
                            <h5 class="mbr-fonts-style display-5">
                                One-Click Payment</h5>
                        </div>

                        <div class="card col-12 col-md-6 col-lg-4">
                            <div class="icon-block">
                                <a href="#">
                                    <span class="mbr-iconfont mbri-responsive"></span>
                                </a>
                            </div>
                            <h5 class="mbr-fonts-style display-5">
                                Portable Technology<br></h5>
                        </div>


                        <style type="text/css">
                        	
                        	h5{
                        		float: left;
                        	}
                        </style>

                        
                    </div>
                </div>
            </div>
    </div>

    
</section>

<section class="mbr-section contacts2 cid-rjE7tJXYSz" id="contacts2-g">
    <!---->
    
    <!---->
    <!--Overlay-->
    
    <!--Container-->
    <div class="container">
        <div class="row">
            <!--Titles-->
            <div class="title col-12">
                <h2 class="align-left mbr-fonts-style display-1">
                    Our Contacts
                </h2>
                
            </div>
            <div class="col-12">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-4">
                        <div class="b b-adress">
                            <h5 class="align-left mbr-fonts-style m-0 display-5">
                                Address:
                            </h5>
                            <p class="mbr-text align-left mbr-fonts-style display-7">
                                Ministry of Micro, Small and Medium Enterprises Udyog Bhawan, Rafi Marg, New Delhi - 110011
                            </p>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="b b-phone">
                            <h5 class="align-left mbr-fonts-style m-0 display-5">
                                Phone:
                            </h5>
                            <p class="mbr-text align-left mbr-fonts-style display-7">+91 011-23061431
                            </p>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="b b-mail">
                            <h5 class="align-left mbr-fonts-style m-0 display-5">
                                E-mail:
                            </h5>
                            <p class="mbr-text align-left mbr-fonts-style display-7">
                                js[dot]sme[at]nic[dot]in</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="cid-rjE7ZQC8fR" id="social-buttons3-k">
    
    

    

    <div class="container">
        <div class="media-container-row">
            <div class="col-md-8 align-center">
                <h2 class="pb-3 mbr-section-title mbr-fonts-style display-2">
                    SHARE THIS PAGE!
                </h2>
                <div>
                    <div class="mbr-social-likes">
                        <a href="https://www.facebook.com/minmsme/"><span class="btn btn-social socicon-bg-facebook facebook mx-2" title="Share link on Facebook">
                            <i class="socicon socicon-facebook"></i>
                        </span></a>
                        <a href="https://twitter.com/minmsme"><span class="btn btn-social twitter socicon-bg-twitter mx-2" title="Share link on Twitter">
                            <i class="socicon socicon-twitter"></i>
                        </span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


  <script src="{% static '/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/popper/popper.min.js' %}"></script>
  <script src="{% static '/tether/tether.min.js' %}"></script>
  <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static '/dropdown/js/script.min.js' %}"></script>
  <script src="{% static '/vimeoplayer/jquery.mb.vimeo_player.js' %}"></script>
  <script src="{% static '/parallax/jarallax.min.js' %}"></script>
  <script src="{% static '/sociallikes/social-likes.js' %}"></script>
  <script src="{% static '/touchswipe/jquery.touch-swipe.min.js' %}"></script>
  <script src="{% static '/theme/js/script.js' %}"></script>
  
  
</body>
</html>